..\x64\Release\winmetamoc.exe Windows.Win32.Foundation > lib\win32\base.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.LibraryLoader > lib\win32\lib.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Memory > lib\win32\mem.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Environment > lib\win32\env.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Registry > lib\win32\reg.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.SystemInformation > lib\win32\sysinfo.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Time > lib\win32\time.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Com > lib\win32\com.lib
..\x64\Release\winmetamoc.exe Windows.Win32.System.Ole > lib\win32\ole.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Globalization > lib\win32\uni.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Graphics.Gdi > lib\win32\gdi.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Security.Cryptography > lib\win32\crypt.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.WindowsAndMessaging > lib\win32\user.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Input.KeyboardAndMouse > lib\win32\input.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Input.Pointer > lib\win32\pointer.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Input.Touch > lib\win32\touch.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Controls > lib\win32\ctrl.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Controls.Dialogs > lib\win32\dlg.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Controls.RichEdit > lib\win32\rich.lib
..\x64\Release\winmetamoc.exe Windows.Win32.UI.Shell > lib\win32\shell.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Storage.FileSystem > lib\win32\storage.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Networking.WinHttp > lib\win32\http.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Networking.WinInet > lib\win32\inet.lib
..\x64\Release\winmetamoc.exe Windows.Win32.Networking.WinSock > lib\win32\sock.lib
..\x64\Release\winmetamoc.exe Windows.Win32.NetworkManagement.Dns > lib\win32\dns.lib
